server:
  port: 8080 # 修改port
#  context-path: /api # 給根路徑(預設為"/")
 
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sa123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.ctbc: debug
  file: logs/dev.log