server:
  port: 8081 # 修改port
  context-path: /api # 給根路徑(預設為"/")
 
logging:
  level:
    root: warn
    com.ctbc: debug
  file: logs/yml.log
  
book:
  name: 從零開始
  author: 我不知道作者是誰
  isbn: ${random.uuid}
  description: ${book.name}，這本書不錯